aroundcomet/aroundcomet/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls) ,
    url(r'^$', RedirectView.as_view(url='/accounts/login/', permanent = True)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^blank/' , include('blank.urls')),


    ]

aroundcomet/blank/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from . import views
from .filters import  UserFilter
from django_filters.views import FilterView
from django.contrib.auth.decorators import login_required, permission_required


urlpatterns = [
    url(r'^main$', login_required(views.Main.as_view()), name ='main'),
    url(r'^create$', login_required(views.form_creating), name='blank-create'),
    url(r'^ticket/(?P<pk>\d+)$', login_required(views.MyTicket.as_view()), name='my-ticket'),
    url(r'^search$',  login_required(FilterView.as_view(filterset_class=UserFilter,  template_name = 'search.html')), name ='search'),
    url(r'^edit/(?P<pk>\d+)$', login_required(views.Edit.as_view()), name='edit'),
    url(r'^statusopen$', login_required(views.BlankStatusOpen.as_view()), name='statusopen'),
    url(r'^test/', include('router.urls'))


]

aroundcomet/router/urls.py
from .views import Test
from django.conf.urls import url , include

urlpatterns = [
                url(r'^tes$', Test.as_view(), name='tes'),
                ]

aroundcomet/blank/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.admin import User
from django.urls import reverse
from django.utils.html import format_html
#import datetime

class Profile(models.Model):
    date_creating = models.DateField(help_text='Дата регистрации', null=True, blank=True, default=now)
    name = models.CharField(help_text='Введите имя абонента', max_length=15)
    surname = models.CharField(help_text='Введите фамилию абонента',max_length=15)
    patronymic = models.CharField(help_text='Введите отчество абонента', max_length=20)
    #passport_data = models.CharField(help_text='Паспортные данные',max_length=100)
    address = models.CharField(help_text='Улица/Массив', max_length=20,)
    home = models.CharField(help_text='Введите номер дома', max_length=5)
    flat = models.CharField(help_text='Введите номер квартиры', max_length=5,)
    contact_number = models.CharField(help_text='Контактный номер абонента', max_length=30,)
    prefering_connection = models.DateField(help_text='Предпочитаемая дата подключения')
    datetimerange = models.DateField(help_text='Для фильтрации дат с отметками , ОТ -- К', null=True, blank=True, default=now)
    manager = models.ForeignKey(User,blank=True, null=True, on_delete=models.SET_NULL,)

    class Meta:
        permissions = (
            ("can_see_all_blank" , "View all blanks"),
                      )

    tarrif_plans = (
        ('Скоростной 40', 'Скоростной 40'),
        ('Скоростной 60', 'Скоростной 60'),
        ('Скоростной 80', 'Скоростной 80'),
        ('Скоростной 100', 'Скоростной 100'),
        ('Скоростной 120','Скоростной 120'),
        ('Скоростной 140', 'Скоростной 140'),
        ('Скоростной 160', 'Скоростной 160'),
        ('Скоростной 200', 'Скоростной 200'),
        ('Скоростной 240', 'Скоростной 240'),
    )

    tarrif = models.CharField(blank=True ,choices= tarrif_plans , null=True , max_length=15)


    blank_status = (
        ('Открыта', 'Открыта'),
        ('Закрыта', 'Закрыта'),
                    )

    status = models.CharField(max_length=15, choices=blank_status, blank=True , null=True)



    def get_absolute_url(self):
        return reverse('my-ticket', args=[str(self.id)])



    def get_edit_url(self):
        return reverse('edit', args=[str(self.id)])



    def __str__(self):
        return self.name + " "+" "+ self.surname



    def colored_status(self):
        if self.status == 'Открыта':
            return format_html(
                '<span style="color: #006400;">{}</span>',
                self.status
        )

        else:
            return format_html(
                '<span style="color: #FF0000;">{}</span>',
                self.status
        )

aroundcomet/router/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.admin import User


class Router(models.Model):
    date = models.DateField(default=now)
    model = models.CharField(max_length=15)
    SN = models.CharField(max_length=20)
    username = models.ForeignKey('Username', on_delete=models.SET_NULL,null=True)
    manager = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)

    def __str__(self):
        return self.model


class Username(models.Model):
    login = models.CharField(max_length=15)
    contract = models.CharField(max_length=15)
    def __str__(self):
        return self.login

aroundcomet/blank/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic import CreateView , DetailView , UpdateView
from .models import Profile
from .form import ProfileForm
from django.http import HttpResponseRedirect , HttpResponse
from django.core.urlresolvers import reverse
# Create your views here.



'''         
    Создание форм при помощи класса 
    
class BlankCreate(CreateView):
    model = Profile
    template_name = 'req_create.html'
    fields = '__all__'
    initial = {'date_creating':now} 
                                        '''

class Edit(UpdateView):
    model = Profile
    form_class = ProfileForm
    #form_class = ProfileForm
    template_name = 'edit.html'



class Main(generic.ListView):
    model = Profile
    paginate_by = 15
    template_name = 'main.html'
    def get_queryset(self):
        return Profile.objects.filter(manager=self.request.user)

class BlankStatusOpen(generic.ListView):
    mdodel = Profile
    paginate_by = 15
    template_name = 'blankstatusopen.html'
    def get_queryset(self):
        return Profile.objects.filter(status='Открыта')



class MyTicket(generic.DetailView):
    model = Profile
    template_name = 'ticket.html'



##############################
def form_creating(request):
    profile = Profile()
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            profile.date_creating = form.cleaned_data['date_creating']
            profile.name = form.cleaned_data['name']
            profile.surname = form.cleaned_data['surname']
            profile.patronymic = form.cleaned_data['patronymic']
            profile.home = form.cleaned_data['home']
            profile.flat = form.cleaned_data['flat']
            profile.contact_number = form.cleaned_data['contact_number']
            profile.prefering_connection = form.cleaned_data['prefering_connection']
            profile.tarrif = form.cleaned_data['tarrif']
            profile.address = form.cleaned_data['address']
            profile.status = form.cleaned_data['status']
            profile.manager = request.user
            profile.save()
            return HttpResponseRedirect(reverse('main'))
        else:
            form = ProfileForm(request.POST)
            return render(request, 'req_create.html', {'form':form, 'profile': profile})



    else:
        form = ProfileForm()
        return render(request, 'req_create.html', {'form':form, 'profile': profile})




########################################################################

aroundcomet/router/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.views import generic
from .models import Username,Router
from django.views.generic import CreateView , DetailView , UpdateView
from django.http import HttpResponseRedirect , HttpResponse
from django.core.urlresolvers import reverse


class Test(generic.ListView):
    model = Router
    template_name = 'test.html'
    

aroundcomet/templates/blankstatusopen.html
{% extends 'main.html' %}

aroundcomet/templates/edit.html
{% extends 'main.html' %}

{% load static %}

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


	<body class="body2">
	{% block content %}
	<div class="row" >
	    <div class="col-lg-7 col-md-12  col-sm-12 ">
	      <div class="reg">
		        <form class="form-horizontal" action="" method="post" name="contact_form">
					 {% csrf_token %}


					 {% if form.name.errors %}
					<p><strong> <font color="#ca1c1a"> {{form.name.errors}} </font> </strong></p>
					 {% endif %}

					<div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Имя</label>
				      <div class="col-sm-7">
				        {{form.name}}
					  </div>
					</div>



					{% if form.surname.errors %}
					<p><strong> <font color="#ca1c1a"> {{form.surname.errors}} </font> </strong></p>
					 {% endif %}



				    <div>
				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Фамилия:</label>
				      <div class="col-sm-7">
				        {{form.surname}}
				      </div>
					</div>

					{% if form.patronymic.errors %}
					<p><strong> <font color="#ca1c1a"> {{form.patronymic.errors}} </font> </strong></p>
					 {% endif %}



				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Отчество:</label>
				      <div class="col-sm-7">
						{{form.patronymic}}
				      </div>
				    </div>

					{% if form.address.errors %}
					<p><strong> <font color="#ca1c1a"> {{form.address.errors}} </font> </strong></p>
					 {% endif %}

				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Адресс:</label>
				     	<div class="col-sm-7">
						  {{form.address}}
				      </div>
					</div>


					{% if form.home.errors %}
					<p><strong> <font color="#ca1c1a"> {{form.home.errors}} </font> </strong></p>
					{% endif %}

				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Дом:</label>
				      <div class="col-sm-7">
						  {{form.home}}
				      </div>
				    </div>

					{% if form.flat.errors %}
					<p><strong> <font color="#ca1c1a"> {{form.flat.errors}} </font> </strong></p>
					 {% endif %}

				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Квартира:</label>
				      <div class="col-sm-7">
						  {{form.flat}}
				      </div>
				    </div>


					{% if form.contact_number.errors %}
					<p><strong> <font color="#ca1c1a"> {{form.contact_number.errors}} </font> </strong></p>
					 {% endif %}
				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Контактный телефон:</label>
				      <div class="col-sm-7">
						  {{form.contact_number}}
				      </div>
				    </div>



				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Время подключения:</label>
				      <div class="col-sm-7">
							{{form.prefering_connection}}
				      </div>
				    </div>
				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Тарифный план:</label>
				      <div class="col-sm-7">
						  {{form.tarrif}}
				      </div>
				    </div>
				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Статус заявки:</label>
				      <div class="col-sm-7">
						  {{form.status}}
					  </div>

				      </div>
				    </div>
				    <div class="form-group">
				      <div class="col-sm-offset-6 col-sm-7">
				        <button type="submit" class="btn btn-info btn-md">Изменить</button>
				      </div>
				    </div>
				</form>
	      </div>
	    </div>
	  </div>
	{% endblock %}

aroundcomet/templates/main.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}

	<meta charset="utf-8">
	<title>Our Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'startup/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'startup/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'startup/css/bootstrap-theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'startup/css/bootstrap.min.css' %}">

    <script src="{% static 'startup/js/jquery.min.js' %}"></script>
    <script src="{% static 'startup/js/bootstrap.min.js' %}"></script>

</head>
<body>
	<div class="row" style="margin-right: 0;"> ]
        <div>

        </div>
	<div class="col-lg-12" style="background-color:black;">
		<h1 align="center" style="margin-bottom: 60px; color: #4ddbff; ">Welcome</h1>
		  		<div class='top'>
						{% if user.is_authenticated %}
	                	<h3 style="margin: 0 0 0 28.5%; color: #4ddbff;"> <p> {{user.get_username}}</h3>
						{% endif %}

					<!--<button type="button" onclick='location.href="{% url "logout"%}?next={{request.path}}"' class="btn btn-info  btn-md">Выход</button> -->


				</div>
	            <hr>
	</div>
        {% block sidebar %}
  		<div class="col-lg-3 col-md-3 col-sm-4" style="margin-top:3vh">
  			<div class="navigation">
                <ul class="nav list-group">
                    <li>
                        <a class="list-group-item" href="{% url 'main' %}"><i class="icon-home icon-1x"></i>Главная страница</a>
                    </li>

                    <li>
						<a class="list-group-item" href="{% url 'blank-create' %}"><i class="icon-home icon-1x"></i>Создать заявку</a>
                    </li>
                    <li>
                        <a class="list-group-item" href="{% url 'statusopen' %}"><i class="icon-home icon-1x"></i>Открытые заявки</a>
                    </li>
                        <a class="list-group-item" href="{% url 'tes' %}"><i class="icon-home icon-1x"></i>Аренда оборудования</a>
                    <li>
                        <a class="list-group-item" href="{% url 'search' %}"><i class="icon-home icon-1x"></i>Поиск</a>
                    </li>
                    <li>
                        <a class="list-group-item" href="{% url "logout"%}?next={{request.path}}"><i class="icon-home icon-1x"></i>Выход</a>

                </li>
                </ul>
            </div>
        </div>
        {% endblock %}

        {% block content %}
        <div class="col-lg-9 pull-right col-md-9 col-sm-8" style="margin-top:3vh">
        	<div class="wrapper">
			{% for prof in profile_list %}
				<li>
					<a href="{{prof.get_absolute_url}}">{{prof.name}}</a>
				</li>
			{% endfor %}

	        </div>


	        <div class="col-lg-12 col-md-12 col-sm-12" style="margin-top: 10px;">

	  {% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">назад</a>
              {% endif %}
              <span class="page-current">
                  страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">далее</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}



	        </div>
	      </div>
	</div>
    {% endblock %}


</body>
</html>

aroundcomet/templates/req_create.html
{% extends 'main.html' %}

{% load static %}

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


	<body class="body2">
	{% block content %}
	<div class="row" >
	    <div class="col-lg-7 col-md-12  col-sm-12 ">
	      <div class="reg">
		        <form class="form-horizontal" action="" method="post" name="contact_form">
					 {% csrf_token %}


					 {% if form.name.errors %}
					<p><strong> <font color="#ca1c1a"> {{form.name.errors}} </font> </strong></p>
					 {% endif %}

					<div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Имя:</label>
				      <div class="col-sm-7">
				        {{form.name}}
					  </div>
					</div>



					{% if form.surname.errors %}
					<p><strong> <font color="#ca1c1a"> {{form.surname.errors}} </font> </strong></p>
					 {% endif %}



				    <div>
				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Фамилия:</label>
				      <div class="col-sm-7">
				        {{form.surname}}
				      </div>
					</div>

					{% if form.patronymic.errors %}
					<p><strong> <font color="#ca1c1a"> {{form.patronymic.errors}} </font> </strong></p>
					 {% endif %}



				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Отчество:</label>
				      <div class="col-sm-7">
						{{form.patronymic}}
				      </div>
				    </div>

					{% if form.address.errors %}
					<p><strong> <font color="#ca1c1a"> {{form.address.errors}} </font> </strong></p>
					 {% endif %}

				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Адресс:</label>
				     	<div class="col-sm-7">
						  {{form.address}}
				      </div>
					</div>


					{% if form.home.errors %}
					<p><strong> <font color="#ca1c1a"> {{form.home.errors}} </font> </strong></p>
					{% endif %}

				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Дом:</label>
				      <div class="col-sm-7">
						  {{form.home}}
				      </div>
				    </div>

					{% if form.flat.errors %}
					<p><strong> <font color="#ca1c1a"> {{form.flat.errors}} </font> </strong></p>
					 {% endif %}

				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Квартира:</label>
				      <div class="col-sm-7">
						  {{form.flat}}
				      </div>
				    </div>


					{% if form.contact_number.errors %}
					<p><strong> <font color="#ca1c1a"> {{form.contact_number.errors}} </font> </strong></p>
					 {% endif %}
				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Контактный телефон:</label>
				      <div class="col-sm-7">
						  {{form.contact_number}}
				      </div>
				    </div>



				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Время подключения:</label>
				      <div class="col-sm-7">
							{{form.prefering_connection}}
				      </div>
				    </div>
				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Тарифный план:</label>
				      <div class="col-sm-7">
						  {{form.tarrif}}
				      </div>
				    </div>
				    <div class="form-group">
				      <label class="control-label col-sm-4" for="email"> Статус заявки:</label>
				      <div class="col-sm-7">
						  {{form.status}}
					  </div>

				      </div>
				    </div>
				    <div class="form-group">
				      <div class="col-sm-offset-6 col-sm-7">
				        <button type="submit" class="btn btn-info btn-md">Зарегистрировать</button>
				      </div>
				    </div>
				</form>
	      </div>
	    </div>
	  </div>
	{% endblock %}

aroundcomet/templates/search.html
{% extends 'main.html' %}
    {% block content %}
   <body>

    <div class="col-lg-8 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1" style="margin-top: 5vh; ">
	    <div class="ser" style="margin-left: -80px;">
	        <form method="get">
	          	<ul class="searchform">
		          	<div class="span1">
		          		<div class="col-lg-3 col-md-2 col-sm-2">

				            <li class="date">
								<strong> {{ filter.form.date_creating.label }} </strong>
								         {{ filter.form.date_creating }}
				            </li>

				            <li class="name">
				             	<strong> {{ filter.form.name.label }} </strong>
								{{ filter.form.name }}
				            </li>

				            <li class="surname">
				            	<strong> {{ filter.form.surname.label }} </strong>
								{{ filter.form.surname }}
				            </li>

				            <li class="address">
				             	<strong> {{ filter.form.address.label }} </strong>
								{{ filter.form.address }}
				            </li>
		            	</div>
	            	</div>

		            <div class="span2">
			            <div class="col-lg-3 col-md-3 col-sm-2">
				            <li class="manager">
				              	<strong> {{ filter.form.manager.label }} </strong>
								{{ filter.form.manager }}
				            </li>

				            <li class="status">
								<strong> {{ filter.form.status.label }} </strong>
								{{ filter.form.status }}

				            </li>

				            <li class="tarrif">
							<strong> {{ filter.form.tarrif.label }} </strong>
								{{ filter.form.tarrif }}

				            </li>
		            	</div>
	            	</div>

		            <div class="span3">
			            <div class="col-lg-3 col-md-3 col-sm-2">
				            <li class="dtm">
						<strong> {{ filter.form.datetimerange.label }} </strong>
								{{ filter.form.datetimerange }}

				            </li>

				        </div>
				    </div>

                    <div class="col-lg-12 col-md-8 col-sm-6">
					    <div class="span4">
					    	{% for value in filter.qs %}
							<p>

								<a href="{{ value.get_absolute_url }}" >{{value.name}}</a>

					    	</p>
							{% endfor %}
					    </div>

					    <div class="span5">
						    <li>
					        	<button type="submit" class="btn btn-info">
									<span class="glyphicon glyphicon-search"></span> Search
								</button>
					        </li>
				        </div>
			        </div>

	        	</ul>
	        </form>
	    </div>
	</div>

</body>
    {% endblock %}

aroundcomet/templates/test.html
{% for route in router_list %}

{{route}}

{%endfor%}

aroundcomet/templates/ticket.html
{% extends 'main.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% block content %}

    <div class="red">
        <div class="col-lg-6  col-md-5 col-sm-4" style="margin-top:3vh">
            <ul>
                <li>
                    <p><strong>Имя :</strong> {{profile.name}}</p>
                    <p><strong>Фамилия:</strong> {{profile.surname}}</p>
                    <p><strong>Отвчество:</strong> {{profile.patronymic}} </p>
                    <p><strong>Адрес:</strong> {{profile.address}} </p>
                    <p><strong>Дом:</strong> {{profile.home}}</p>
                    <p><strong>Квартира:</strong>{{profile.flat}}</p>

                    <p><strong>Менеджер :</strong> {{profile.manager}}</p>
                    <p><strong>Контактный номер </strong> : {{profile.contact_number}} </p>
                    <p><strong>Тарифный план  </strong> : {{profile.tarrif}} </p>


                    {% if profile.status == 'Закрыта' %}
                    <p style="color: red ;"><strong>Статус : {{profile.status}} </strong></p>
                    {% elif profile.status == 'Открыта' %}
                    <p style="color: green ;"><strong>Статус : {{profile.status}} </strong></p>
                    {% endif %}
                    <button class="btn" type="button" onclick='location.href="{{profile.get_edit_url}}"' > Редактировать</button>
                </li>
            </ul>
        </div>
    </div>


{% endblock %}
</html>